char* token_str[] = {
	"INT",
	"FLOAT",
	"SEMI",
	"COMMA",
	"ASSIGNOP",
	"RELOP",
	"PLUS",
	"MINUS",
	"STAR",
	"DIV",
	"AND",
	"OR",
	"DOT",
	"NOT",
	"TYPE",
	"LP",
	"RP",
	"LB",
	"RB",
	"LC",
	"RC",
	"STRUCT",
	"RETURN",
	"IF",
	"ELSE",
	"WHILE",
        "EXTERN", 
	"ID",
	"Program",
	"ExtDefList",
	"ExtDec",
	"ExtDef",
	"ExtDecList",
	"Specifier",
	"StructSpecifier",
	"OptTag",
	"Tag",
	"VarDec",
	"FunDec",
	"VarList",
	"ParamDec",
	"CompSt",
	"StmtList",
	"Stmt",
	"DefList",
	"Def",
	"DecList",
	"Dec",
	"Exp",
	"Args",
        "error",
        "READ",
        "WRITE"
};


char *sem_err[] = {
    "Undefined error 0\n",
    "Error type 1 at line %d: The variable \"%s\" not declared.\n",
    "Error type 2 at line %d: The function \"%s\" not declared.\n",
    "Error type 3 at line %d: Conflicting or reduplicating definition of variable \"%s\".\n",
    "Error type 4 at line %d: Redifinition of function \"%s\".\n", 
    "Error type 5 at line %d: Types do not match of assignment.\n",
    "Error type 6 at line %d: Lvalue required as left operand of assignment.\n", 
    "Error type 7 at line %d: Types mistake.\n",
    "Error type 8 at line %d: Return type can not match.\n", 
    "Error type 9 at line %d: Function call with unmatched arguements.\n", 
    "Error type 10 at line %d: Non-array type can not do [] operator.\n", 
    "Undefined error 11\n",
    "Error type 12 at line %d: Only int can be the index of an array.\n",
    "Error type 13 at line %d: Non-struct can not do . operator.\n", 
    "Undefined error 14\n",
    "Error type 15 at line %d: Struct members can not be initialized.\n", 
    "Error type 16 at line %d: Variable name conflicts.\n",
    "Error type 17 at line %d: Types not defined.\n", 
    "Undefined error 18\n",
    "Error type 19 at line %d: Conflicting fuction declarations.\n" ,
    "Error type 20 at line %d: Non-int as a bool retval.\n"
};

